language: python

addons:
    apt_packages:
        - enchant
        - aspell
        - aspell-en

matrix:
  include:
    - name: "Lint"
      python: "3.7"
      env: TOXENV=lint
      dist: xenial

#    - name: "3.7"
#      os: windows
#      language: shell
#      before_install: choco install python
#      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH TOXENV=codecov

install:
  - pip3 install tox

script:
  - tox