name: Tests

on:
  push:
  pull_request:
  release:
  schedule:
    # Every Thursday at 1 AM
    - cron: '0 1 * * 4'

jobs:

  Tests:
    runs-on: ${{ matrix.os || 'windows-latest' }}
    name: ${{ startsWith(matrix.toxenv, 'py') && format('{0}_{1}', matrix.python-version, matrix.python-arch) || format('{0} ({1}_{2})', matrix.toxenv, matrix.python-version, matrix.python-arch) }} ${{ matrix.optional && '[OPTIONAL]' }}
    continue-on-error: ${{ matrix.optional || false }}

    strategy:
      fail-fast: false

      matrix:
        python-version: ['2.7', '3.5', '3.6', '3.7', '3.8', '3.9', '3.10', '3.11']
        python-arch: ['x86', 'x64']
        toxenv: [pywin]


        include:

          - toxenv: lint
            python-version: 3.x
            python-arch: x64
            os: ubuntu-latest

          - toxenv: coverage
            python-version: 3.x
            python-arch: x64

          - python-version: '3.12-dev'
            optional: true
            python-arch: x86
            toxenv: pywin

          - python-version: '3.12-dev'
            optional: true
            python-arch: x64
            toxenv: pywin

    env:
      TOXENV: ${{ matrix.toxenv }}
      TOXPYTHON: python${{ matrix.toxpython || matrix.python-version }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.python-arch }}

      - name: Install tox
        run: pip install tox

      - name: Run tox
        run: tox -- --verbose

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        if: ${{ matrix.toxenv == 'coverage' }}
